# docker-compose.full.yml
# Configuração completa com Prometheus e Grafana (OPCIONAL)
# Use este arquivo se quiser instalar também Prometheus e Grafana
# Comando: docker-compose -f docker-compose.full.yml up -d

version: '3.8'

services:
  pg_monitor:
    build: .
    container_name: pg_monitor
    restart: unless-stopped
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
    volumes:
      - ./config:/app/config:ro
      - ./logs:/var/log/pg_monitor
    ports:
      - "9394:9394"
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9394/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pg_monitor_scheduler:
    build: .
    container_name: pg_monitor_scheduler
    restart: unless-stopped
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - ./config:/app/config:ro
      - ./logs:/var/log/pg_monitor
      - ./crontab:/etc/crontabs/pgmonitor:ro
    command: ["crond", "-f", "-l", "2"]
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./examples/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboards:/etc/grafana/provisioning/dashboards:ro
    ports:
      - "3000:3000"
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
