# docker-compose.yml
# Configuração simplificada: apenas pg_monitor
# PostgreSQL deve estar instalado externamente no servidor
version: '3.8'

services:
  pg_monitor:
    build: .
    container_name: pg_monitor
    restart: unless-stopped
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
    volumes:
      - ./config:/app/config:ro
      - ./logs:/var/log/pg_monitor
    ports:
      - "9394:9394"
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9394/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pg_monitor_scheduler:
    build: .
    container_name: pg_monitor_scheduler
    restart: unless-stopped
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - ./config:/app/config:ro
      - ./logs:/var/log/pg_monitor
      - ./crontab:/etc/crontabs/pgmonitor:ro
    command: ["crond", "-f", "-l", "2"]
    network_mode: "host"
