# pg_monitor_config.yml

# --- Configurações do Banco de Dados ---
database:
  host: "127.0.0.1" # Altere para o IP ou hostname do seu servidor PostgreSQL
  port: 5432            # Porta do PostgreSQL
  name: "postgres"         # Altere para o nome do seu banco de dados 
# --- Configurações de E-mail ---
email:
  sender_email: "monitor.postgresql.32@gmail.com" # Altere para o seu e-mail remetente
  receiver_email: "joaovic32@gmail.com" # Altere para o e-mail que receberá os alertas
  smtp_address: "smtp.gmail.com"  # Servidor SMTP do seu provedor de e-mail
  smtp_port: 587                  # Porta SMTP (587 para TLS/STARTTLS)
  smtp_domain: "gmail.com"        # Domínio do seu servidor SMTP (ex: gmail.com, outlook.com)

# --- Limiares de Alerta ---
thresholds:
  iostat_threshold_kb_s: 50000    # Limiar de I/O de disco em KB/s
  iostat_device: "vda" # Ajuste para o seu dispositivo de disco principal (ex: vda, sda, nvme0n1)
  cpu_threshold_percent: 80 # Alerta se o uso da CPU exceder 80%
  query_alert_threshold_minutes: 5 # Alerta se a consulta demorar mais de 5 minutos
  query_kill_threshold_minutes: 10 # Mata a consulta se demorar mais de 10 minutos (se auto_kill for true)
  heap_cache_hit_ratio_min: 95 # Alerta se a taxa de acertos do cache de heap estiver abaixo de 95%
  index_cache_hit_ratio_min: 90 # Alerta se a taxa de acertos do cache de índice estiver abaixo de 90%
  table_growth_threshold_percent: 20 # Alerta se a tabela crescer mais de 20% desde a última verificação (requer histórico)
  
  # Novos limiares para melhorias
  disk_space_threshold_percent: 90 # Alerta se o uso do espaço em disco na partição do diretório de dados exceder 90%
  replication_lag_bytes_threshold: 104857600 # 100 MB (100 * 1024 * 1024 bytes)
  replication_lag_time_threshold_seconds: 300 # 5 minutos (300 segundos)
  
cooldown:
  alert_cooldown_minutes: 60 # Não enviar o mesmo tipo de alerta novamente dentro de 60 minutos
  last_alert_file: "/tmp/pg_monitor_last_alerts.json" # Caminho para armazenar os carimbos de data/hora do último alerta
  last_deadlock_file: "/tmp/pg_monitor_last_deadlock_count.json" # Caminho para armazenar o contador do último deadlock

# --- Configuração de Log (para os logs do próprio script) ---
logging:
  log_file: "/var/log/pg_monitor/pg_monitor.log" # Caminho completo para o arquivo de log do script. Certifique-se de que o diretório existe e é gravável.
  log_level: "info" # Nível de log (ex: "info", "debug", "error")

# --- Caminho dos Logs do PostgreSQL (para varreduras de segurança) ---
postgresql_logs:
  path: "/var/lib/postgresql/16/main/log" # Caminho completo para o diretório de log do PostgreSQL (ex: /var/log/postgresql ou /var/lib/pgsql/data/log)
  file_pattern: "postgresql-*.log" # Padrão de nome do arquivo de log (ex: postgresql-*.log, postgresql-YYYY-MM-DD_*.log)

# --- Recursos Adicionais ---
features:
  auto_kill_rogue_processes: true # Define se o script deve tentar matar processos "rogue" (longos/travados) automaticamente